'use client';

import { useEffect, useRef, useState, type DragEvent } from 'react';
import Link from 'next/link';
import { createSupabaseBrowserClient, isSupabaseConfigured } from '@/lib/supabase/client';
import { useWorldCustomization, type MediaPlacement, type WorldKey } from '@/components/studio/WorldCustomizationProvider';
import { CREATOR_STUDIO_KEY, type CreatorConfig, defaultCreatorConfig, loadCreatorConfig } from '@/lib/creatorStudio';

const pages: Array<{key:'home'|WorldKey;label:string;path:string}> = [
  {key:'home',label:'Homepage',path:'/'},{key:'melodic',label:'Melodic',path:'/worlds/melodic'},
  {key:'two-harmonic',label:'2 Harmonic',path:'/worlds/two-harmonic'},{key:'fried-em',label:'Fried Em',path:'/worlds/fried-em'},
  {key:'schmackinn',label:'Schmackinn',path:'/worlds/schmackinn'},
];
const fonts=['Arial Black, Impact, sans-serif','Arial, Helvetica, sans-serif','Georgia, Times New Roman, serif','Trebuchet MS, Arial, sans-serif','Courier New, monospace'];
type HomeMediaTarget='background'|'logo'|'source'|'world-icon';

export default function CreatorStudioPage(){
 const {settings,updateWorld,updateLabel,addMedia,removeMedia,cloudStatus}=useWorldCustomization();
 const [pageKey,setPageKey]=useState<'home'|WorldKey>('home'); const [home,setHome]=useState<CreatorConfig>(defaultCreatorConfig);
 const [selectedHomeWorld,setSelectedHomeWorld]=useState(0); const [tab,setTab]=useState<'content'|'style'|'media'|'motion'|'publish'>('content');
 const [homeMediaTarget,setHomeMediaTarget]=useState<HomeMediaTarget>('background'); const [worldPlacement,setWorldPlacement]=useState<MediaPlacement>('background');
 const [uploading,setUploading]=useState(false); const [message,setMessage]=useState(''); const [externalVideo,setExternalVideo]=useState(''); const [revision,setRevision]=useState(0);
 const fileRef=useRef<HTMLInputElement>(null); const selectedPage=pages.find((item)=>item.key===pageKey)!; const activeWorld=pageKey==='home'?null:settings[pageKey]; const selectedCard=home.worlds[selectedHomeWorld];
 useEffect(()=>setHome(loadCreatorConfig()),[]);
 useEffect(()=>{if(pageKey!=='home')return;localStorage.setItem(CREATOR_STUDIO_KEY,JSON.stringify(home));window.dispatchEvent(new Event('harmonic-creator-update'));const timer=window.setTimeout(()=>setRevision(v=>v+1),180);return()=>window.clearTimeout(timer)},[home,pageKey]);
 useEffect(()=>{if(pageKey==='home')return;const timer=window.setTimeout(()=>setRevision(v=>v+1),180);return()=>window.clearTimeout(timer)},[settings,pageKey]);
 const previewUrl=`${selectedPage.path}?studioPreview=1&r=${revision}`;
 const patchHome=<K extends keyof CreatorConfig>(key:K,value:CreatorConfig[K])=>setHome(c=>({...c,[key]:value}));
 const patchCard=(key:keyof typeof selectedCard,value:string|string[]|boolean)=>setHome(c=>({...c,worlds:c.worlds.map((item,index)=>index===selectedHomeWorld?{...item,[key]:value}:item)}));

 async function uploadFiles(files:FileList|File[]){
  const list=Array.from(files).filter(file=>file.type.startsWith('image/')||file.type.startsWith('video/')); if(!list.length){setMessage('Drop a JPG, PNG, WEBP, GIF, MP4, WEBM, or MOV file.');return}
  setUploading(true);setMessage('');
  try{const supabase=createSupabaseBrowserClient();for(const file of list){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'-');const path=`studio/${String(pageKey)}/${Date.now()}-${safe}`;let url='';
   if(isSupabaseConfigured){const upload=await supabase.storage.from('world-media').upload(path,file,{upsert:false,contentType:file.type});if(upload.error)throw upload.error;url=supabase.storage.from('world-media').getPublicUrl(path).data.publicUrl;await supabase.from('assets').insert({title:file.name,asset_type:file.type.startsWith('video/')?'video':'image',world:String(pageKey),bucket:'world-media',path,public_url:url});}
   else url=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)});
   const kind=file.type.startsWith('video/')?'video':'image';
   if(pageKey==='home'){if(homeMediaTarget==='background')setHome(c=>({...c,backgroundMedia:url,backgroundMediaKind:kind}));else if(homeMediaTarget==='logo')setHome(c=>({...c,logoMedia:url}));else if(homeMediaTarget==='source')setHome(c=>({...c,sourceMedia:url}));else patchCard('iconMedia',url)}
   else addMedia(pageKey,{name:file.name,url,kind,placement:worldPlacement,x:50,y:50,width:worldPlacement==='background'?100:42,opacity:100,rotation:0,zIndex:worldPlacement==='background'?0:10,loop:true,muted:true,fit:'cover',motion:'none',duration:6,delay:0});}
   setMessage('Media uploaded and attached to the live draft.');
  }catch(error){setMessage(error instanceof Error?error.message:'Upload failed.')}finally{setUploading(false);if(fileRef.current)fileRef.current.value=''}
 }
 function onDrop(event:DragEvent<HTMLDivElement>){event.preventDefault();void uploadFiles(event.dataTransfer.files)}
 function attachExternalVideo(){if(!externalVideo.trim())return;if(pageKey==='home')setHome(c=>({...c,backgroundMedia:externalVideo.trim(),backgroundMediaKind:'video'}));else addMedia(pageKey,{name:'External background video',url:externalVideo.trim(),kind:'video',placement:worldPlacement,x:50,y:50,width:100,opacity:100,rotation:0,zIndex:0,loop:true,muted:true,fit:'cover',motion:'none',duration:6,delay:0});setExternalVideo('');setMessage('External video attached to the draft.')}

 return <main className="min-h-screen bg-[#050308] text-white"><header className="sticky top-0 z-50 flex flex-wrap items-center justify-between gap-4 border-b border-white/10 bg-black/85 px-5 py-4 backdrop-blur-2xl"><div><p className="text-[10px] font-black uppercase tracking-[.28em] text-purple-300/60">Harmonic OS</p><h1 className="text-2xl font-black">Creator Studio</h1></div><div className="flex gap-2"><Link href="/" className="rounded-full border border-white/15 px-4 py-2 text-xs font-black">View Site</Link><span className="rounded-full bg-purple-300 px-4 py-2 text-xs font-black text-black">{cloudStatus}</span></div></header>
 <div className="grid min-h-[calc(100vh-73px)] xl:grid-cols-[230px_420px_1fr]">
  <aside className="border-r border-white/10 bg-black/35 p-4"><p className="mb-3 text-[10px] font-black uppercase tracking-[.24em] text-white/35">Edit Page / World</p><div className="grid gap-2">{pages.map(item=><button key={item.key} onClick={()=>{setPageKey(item.key);setTab('content')}} className={`rounded-2xl border p-4 text-left ${pageKey===item.key?'border-purple-300 bg-purple-300/15':'border-white/10 bg-white/[.025]'}`}><b>{item.label}</b><span className="mt-1 block text-xs text-white/40">Full visual controls</span></button>)}</div><Link href={`/studio/design/phase-4${pageKey==='home'?'':`?world=${pageKey}`}`} className="mt-5 block rounded-2xl border border-purple-300/35 bg-purple-300/10 p-4 text-sm font-black">Advanced layout, motion & versions →</Link></aside>
  <section className="border-r border-white/10 bg-[#09060d] p-4"><div className="mb-4 flex gap-2 overflow-x-auto">{(['content','style','media','motion','publish'] as const).map(item=><button key={item} onClick={()=>setTab(item)} className={`rounded-full px-4 py-2 text-xs font-black capitalize ${tab===item?'bg-white text-black':'border border-white/10'}`}>{item}</button>)}</div>
   {tab==='content'&&<div className="grid gap-4">{pageKey==='home'?<><Field label="Brand name" value={home.brandName} onChange={v=>patchHome('brandName',v)}/><Field label="Eyebrow" value={home.eyebrow} onChange={v=>patchHome('eyebrow',v)}/><Field label="Headline" value={home.headline} onChange={v=>patchHome('headline',v)}/><Field label="Tagline" value={home.tagline} onChange={v=>patchHome('tagline',v)}/><Area label="Overview" value={home.overviewText} onChange={v=>patchHome('overviewText',v)}/><div className="rounded-2xl border border-white/10 p-4"><p className="text-xs font-black uppercase tracking-[.18em] text-white/45">Homepage World Cards</p><div className="mt-3 flex flex-wrap gap-2">{home.worlds.map((item,index)=><button key={item.id} onClick={()=>setSelectedHomeWorld(index)} className={`rounded-full px-3 py-2 text-xs font-black ${index===selectedHomeWorld?'bg-purple-300 text-black':'border border-white/15'}`}>{item.name}</button>)}</div><div className="mt-4 grid gap-3"><Field label="Prompt" value={selectedCard.prompt} onChange={v=>patchCard('prompt',v)}/><Field label="Name" value={selectedCard.name} onChange={v=>patchCard('name',v)}/><Field label="Frequency" value={selectedCard.frequency} onChange={v=>patchCard('frequency',v)}/><Field label="Fallback icon / emoji" value={selectedCard.icon} onChange={v=>patchCard('icon',v)}/><Area label="Description" value={selectedCard.summary} onChange={v=>patchCard('summary',v)}/><Area label="Dropdown items, one per line" value={selectedCard.items.join('\n')} onChange={v=>patchCard('items',v.split('\n').filter(Boolean))}/></div></div></>:<><Field label="World title" value={activeWorld?.title||''} onChange={v=>updateWorld(pageKey,{title:v})}/><Area label="World subtitle / description" value={activeWorld?.subtitle||''} onChange={v=>updateWorld(pageKey,{subtitle:v})}/><Field label="Eyebrow" value={activeWorld?.labels.eyebrow||''} onChange={v=>updateLabel(pageKey,'eyebrow',v)}/><Field label="Primary CTA" value={activeWorld?.labels.primaryCta||''} onChange={v=>updateLabel(pageKey,'primaryCta',v)}/><Field label="Secondary CTA" value={activeWorld?.labels.secondaryCta||''} onChange={v=>updateLabel(pageKey,'secondaryCta',v)}/></>}</div>}
   {tab==='style'&&<div className="grid gap-4">{pageKey==='home'?<><Select label="Heading font" value={home.headingFont} options={fonts} onChange={v=>patchHome('headingFont',v)}/><Select label="Body font" value={home.bodyFont} options={fonts} onChange={v=>patchHome('bodyFont',v)}/><Range label="Heading scale" value={home.headingScale} min={.7} max={1.4} step={.01} onChange={v=>patchHome('headingScale',v)}/><Range label="Card radius" value={home.cardRadius} min={0} max={44} step={1} onChange={v=>patchHome('cardRadius',v)}/><Color label="Accent" value={home.accent} onChange={v=>patchHome('accent',v)}/><Color label="Background" value={home.background} onChange={v=>patchHome('background',v)}/><Color label="Surface" value={home.surface} onChange={v=>patchHome('surface',v)}/><Color label="Text" value={home.text} onChange={v=>patchHome('text',v)}/></>:<>{(['primary','secondary','accent','background','surface','text','muted','border','glow'] as const).map(key=><Color key={key} label={key} value={activeWorld?.[key]||'#000000'} onChange={v=>updateWorld(pageKey,{[key]:v})}/>)}</>}</div>}
   {tab==='media'&&<div className="grid gap-4">{pageKey==='home'?<><Select label="Attach upload to" value={homeMediaTarget} options={['background','logo','source','world-icon']} onChange={v=>setHomeMediaTarget(v as HomeMediaTarget)}/>{homeMediaTarget==='world-icon'&&<p className="text-xs text-purple-200/60">Selected card: {selectedCard.name}</p>}<Range label="Background overlay" value={home.backgroundOverlay} min={0} max={.9} step={.01} onChange={v=>patchHome('backgroundOverlay',v)}/></>:<Select label="Place upload as" value={worldPlacement} options={['background','hero','logo','floating','section']} onChange={v=>setWorldPlacement(v as MediaPlacement)}/>}<div onDragOver={e=>e.preventDefault()} onDrop={onDrop} onClick={()=>fileRef.current?.click()} className="cursor-pointer rounded-[2rem] border border-dashed border-purple-300/40 bg-purple-300/[.06] p-8 text-center"><b>{uploading?'Uploading…':'Drag & drop media here'}</b><p className="mt-2 text-xs text-white/45">JPG, PNG, WEBP, GIF, MP4, WEBM, MOV</p><input ref={fileRef} hidden type="file" multiple accept="image/*,video/*" onChange={e=>e.target.files&&void uploadFiles(e.target.files)}/></div><div className="rounded-2xl border border-white/10 p-4"><p className="text-xs font-black uppercase tracking-[.18em] text-white/45">External video URL only</p><input value={externalVideo} onChange={e=>setExternalVideo(e.target.value)} placeholder="YouTube, Vimeo, CDN, or hosted video URL" className="mt-3 w-full rounded-xl border border-white/10 bg-black/40 px-4 py-3"/><button onClick={attachExternalVideo} className="mt-3 rounded-full bg-purple-300 px-4 py-2 text-xs font-black text-black">Attach Video</button></div>{pageKey!=='home'&&activeWorld&&<div className="grid gap-2">{activeWorld.media.map(asset=><article key={asset.id} className="flex items-center justify-between gap-3 rounded-2xl border border-white/10 p-3"><div><b>{asset.name}</b><p className="text-xs text-white/40">{asset.kind} · {asset.placement}</p></div><button onClick={()=>removeMedia(pageKey,asset.id)} className="rounded-full border border-red-300/30 px-3 py-2 text-xs font-black text-red-200">Remove</button></article>)}</div>}{message&&<div className="rounded-2xl border border-white/10 bg-white/[.04] p-4 text-sm text-white/65">{message}</div>}</div>}
   {tab==='motion'&&<div className="grid gap-4"><Select label="Entrance" value={pageKey==='home'?'fade':activeWorld?.labels['phase4.motion.entrance']||'fade'} options={['none','fade','slide','scale','blur']} onChange={v=>pageKey!=='home'&&updateLabel(pageKey,'phase4.motion.entrance',v)}/><Select label="Loop motion" value={pageKey==='home'?'none':activeWorld?.labels['phase4.motion.loop']||'float'} options={['none','float','pulse','rotate','breathe']} onChange={v=>pageKey!=='home'&&updateLabel(pageKey,'phase4.motion.loop',v)}/><Select label="Hover response" value={pageKey==='home'?'glow':activeWorld?.labels['phase4.motion.hover']||'scale'} options={['none','scale','tilt','glow','follow']} onChange={v=>pageKey!=='home'&&updateLabel(pageKey,'phase4.motion.hover',v)}/><p className="text-sm text-white/45">Advanced per-layer motion, drag positioning, timelines, and versions remain available through the Advanced button without requiring code.</p></div>}
   {tab==='publish'&&<div className="grid gap-4"><div className="rounded-2xl border border-green-300/20 bg-green-300/[.06] p-4"><b>Live draft is automatic</b><p className="mt-2 text-sm text-white/55">Every change is saved locally and rendered beside you immediately. Publishing controls for every world are available in Advanced layout, motion & versions.</p></div><Link href={`/studio/design/phase-4${pageKey==='home'?'':`?world=${pageKey}`}`} className="rounded-full bg-purple-300 px-5 py-3 text-center font-black text-black">Open Publish & Version Controls</Link></div>}
  </section>
  <section className="relative bg-[#020105] p-4 xl:sticky xl:top-[73px] xl:h-[calc(100vh-73px)]"><div className="flex h-full flex-col overflow-hidden rounded-[2rem] border border-white/10 bg-black"><div className="flex items-center justify-between border-b border-white/10 px-4 py-3"><div><b>Live Draft</b><p className="text-[10px] text-white/40">Updates while you edit</p></div><a href={selectedPage.path} target="_blank" className="rounded-full border border-white/15 px-3 py-2 text-xs font-black">Open ↗</a></div><iframe key={`${pageKey}-${revision}`} src={previewUrl} title={`${selectedPage.label} live draft`} className="h-full min-h-[700px] w-full bg-black"/></div></section>
 </div></main>
}

function Field({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="grid gap-2 text-xs font-black uppercase tracking-[.12em] text-white/45">{label}<input value={value} onChange={e=>onChange(e.target.value)} className="rounded-xl border border-white/10 bg-black/40 px-4 py-3 text-sm font-normal normal-case tracking-normal text-white"/></label>}
function Area({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="grid gap-2 text-xs font-black uppercase tracking-[.12em] text-white/45">{label}<textarea rows={4} value={value} onChange={e=>onChange(e.target.value)} className="rounded-xl border border-white/10 bg-black/40 px-4 py-3 text-sm font-normal normal-case tracking-normal text-white"/></label>}
function Select({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(value:string)=>void}){return <label className="grid gap-2 text-xs font-black uppercase tracking-[.12em] text-white/45">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3 text-sm normal-case tracking-normal text-white">{options.map(option=><option key={option} value={option}>{option}</option>)}</select></label>}
function Color({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="flex items-center justify-between rounded-xl border border-white/10 bg-black/30 p-3 text-xs font-black uppercase tracking-[.12em] text-white/55">{label}<input type="color" value={value} onChange={e=>onChange(e.target.value)} className="h-9 w-14 rounded border-0 bg-transparent"/></label>}
function Range({label,value,min,max,step,onChange}:{label:string;value:number;min:number;max:number;step:number;onChange:(value:number)=>void}){return <label className="grid gap-2 text-xs font-black uppercase tracking-[.12em] text-white/45"><span className="flex justify-between"><span>{label}</span><output>{value}</output></span><input type="range" value={value} min={min} max={max} step={step} onChange={e=>onChange(Number(e.target.value))}/></label>}
