import type { HeartMaterialPreset, UniverseWorld } from './types';

export const universeWorlds: UniverseWorld[] = [
  {
    id: 'two-harmonic',
    name: '2 Harmonic',
    frequency: 'Luxury fashion frequency',
    href: '/worlds/two-harmonic',
    description: 'Royal desert fashion, garment stories, atelier craft, collection memory, and legacy-grade product presentation.',
    color: '#d9b875',
    accent: '#f6ead2',
    orbit: 0,
    delay: '-2s',
    glyph: 'II',
  },
  {
    id: 'melodic',
    name: 'Melodic',
    frequency: 'Music and creative-source frequency',
    href: '/worlds/melodic',
    description: 'A nocturnal studio world for songs, sessions, lyrics, visualizers, archives, and intimate creative memory.',
    color: '#a855f7',
    accent: '#f0abfc',
    orbit: 72,
    delay: '-9s',
    glyph: '♪',
  },
  {
    id: 'fried-em',
    name: 'Fried Em',
    frequency: 'Basketball and competition frequency',
    href: '/worlds/fried-em',
    description: 'A heated blacktop arena of episodes, players, challenges, court maps, heat levels, and competitive stats.',
    color: '#f97316',
    accent: '#fde68a',
    orbit: 144,
    delay: '-16s',
    glyph: 'FE',
  },
  {
    id: 'schmackinn',
    name: 'Schmackinn',
    frequency: 'Food, review, and community frequency',
    href: '/worlds/schmackinn',
    description: 'A neon food district for featured reviews, trending plates, maps, community picks, and tiered food culture.',
    color: '#d946ef',
    accent: '#fb7185',
    orbit: 216,
    delay: '-23s',
    glyph: 'SK',
  },
  {
    id: 'business',
    name: 'Business',
    frequency: 'Entrepreneurship and strategy frequency',
    href: '/worlds/business',
    description: 'A cinematic strategy floor for projects, SmartBox, brand development, funding progress, milestones, and opportunities.',
    color: '#10b981',
    accent: '#fde68a',
    orbit: 288,
    delay: '-30s',
    glyph: 'B',
  },
];

export const heartMaterialPresets: HeartMaterialPreset[] = [
  { name: 'Royal Gold', primary: '#d9b875', secondary: '#fff0c6' },
  { name: 'Black Stone', primary: '#111111', secondary: '#c4a46a' },
  { name: 'Ivory Pearl', primary: '#f4ead7', secondary: '#9a7b45' },
  { name: 'Bronze Heat', primary: '#b77938', secondary: '#ffdc9a' },
  { name: 'Blue Archive', primary: '#36b2cb', secondary: '#f5d26b' },
];
