'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { EditorCommandBar } from '@/components/studio/EditorCommandBar';
import { useEditorHistory } from '@/components/studio/useEditorHistory';
import { Phase4WorldRuntime } from '@/components/studio/Phase4WorldRuntime';
import { useWorldCustomization, type WorldKey, type WorldMediaAsset } from '@/components/studio/WorldCustomizationProvider';
import { WorldEngineShell } from '@/components/WorldEngineShell';
import { getWorldBySlug, type HarmonicWorldConfig } from '@/data/world-engine';

const worlds: Array<{key:WorldKey;label:string;description:string;preview:string;engineSlug?:string}> = [
  {key:'global',label:'Global System',description:'Fallback styling, shared media, and OS-wide behavior.',preview:'/'},
  {key:'home',label:'Homepage',description:'The Harmonic OS entrance and shared navigation language.',preview:'/'},
  {key:'melodic',label:'Melodic',description:'Music, memories, releases, and immersive album language.',preview:'/worlds/melodic',engineSlug:'melodic'},
  {key:'fried-em',label:'Fried Em',description:'Courts, heat, seasons, episodes, rankings, and challenges.',preview:'/worlds/fried-em',engineSlug:'fried-em'},
  {key:'schmackinn',label:'Schmackinn',description:'Flavor City, restaurants, callouts, reviews, and memories.',preview:'/worlds/schmackinn',engineSlug:'schmackin'},
  {key:'two-harmonic',label:'2 Harmonic',description:'The Fashion House, Stitched Melodies, drops, and archives.',preview:'/worlds/2-harmonic',engineSlug:'2-harmonic'},
];

const sharedCopy = [['title','Main Title'],['subtitle','Main Description'],['eyebrow','Eyebrow / Section Label'],['primaryCta','Primary Button'],['secondaryCta','Secondary Button']];
const worldCopy: Partial<Record<WorldKey,string[][]>> = {
  schmackinn:[['systemsTitle','World Systems Title'],['mapTitle','Flavor City Map Title'],['mapDescription','Flavor City Map Description'],['communityTitle','Community Title'],['communityDescription','Community Description'],['archiveTitle','Food Memories Title'],['archiveDescription','Food Memories Description'],['studioTitle','Creator Automation Title']],
  melodic:[['archiveTitle','Memory Archive Title'],['studioTitle','Upload Studio Title'],['communityTitle','Listener Community Title']],
  'fried-em':[['communityTitle','Community / Heat Title'],['archiveTitle','Episode Archive Title'],['studioTitle','Fried Em CMS Title']],
  'two-harmonic':[['archiveTitle','Stitch Archive Title'],['studioTitle','Fashion House Studio Title'],['communityTitle','Community Stories Title']],
};

type Section='identity'|'theme'|'copy'|'media'|'layout'|'motion'|'features'|'publishing';
const sections:Array<{key:Section;label:string;description:string}> = [
  {key:'identity',label:'Identity',description:'World name, description, logo, frequency label, and icon.'},
  {key:'theme',label:'Theme',description:'Colors, typography, background, surfaces, borders, glow, and atmosphere.'},
  {key:'copy',label:'Copy',description:'Page sections, headlines, labels, and calls-to-action.'},
  {key:'media',label:'Media & Layers',description:'Images, GIFs, videos, logos, decorative layers, and background assets.'},
  {key:'layout',label:'Layout',description:'Spacing, alignment, cards, responsive layout, and visibility.'},
  {key:'motion',label:'Motion',description:'Entry animation, hover behavior, transitions, parallax, and reduced motion.'},
  {key:'features',label:'Features',description:'Commerce, audio, community, releases, and world-specific modules.'},
  {key:'publishing',label:'Publishing',description:'Save draft, publish, version history, restore, and production status.'},
];

const blankAsset:Omit<WorldMediaAsset,'id'>={name:'New Layer',url:'',kind:'image',placement:'floating',x:50,y:50,width:28,opacity:100,rotation:0,zIndex:1,loop:true,muted:true,fit:'contain'};
const SECRET_KEY='harmonic-studio-secret-session';
type PendingAction='draft'|'publish'|'upload'|null;
type Viewport='desktop'|'tablet'|'mobile';

export function WorldDesignStudio(){
  const {settings,updateWorld,updateLabel,addMedia,updateMedia,removeMedia,saveDraft,publishWorld,copyToAll,resetWorld,cloudStatus,lastSavedAt}=useWorldCustomization();
  const [world,setWorld]=useState<WorldKey>('schmackinn');
  const [section,setSection]=useState<Section>('identity');
  const [secret,setSecret]=useState('');
  const [draft,setDraft]=useState(blankAsset);
  const [uploading,setUploading]=useState(false);
  const [saving,setSaving]=useState(false);
  const [message,setMessage]=useState('Ready. Edit controls update the preview immediately.');
  const [pending,setPending]=useState<PendingAction>(null);
  const [savedSnapshot,setSavedSnapshot]=useState('');
  const [viewport,setViewport]=useState<Viewport>('desktop');
  const [mobileMode,setMobileMode]=useState<'edit'|'preview'>('edit');
  const [fullscreen,setFullscreen]=useState(false);
  const scrollRef=useRef<HTMLDivElement>(null);
  const active=settings[world];
  const editorHistory=useEditorHistory(active);
  const worldInfo=useMemo(()=>worlds.find((item)=>item.key===world)!,[world]);
  const extraCopy=worldCopy[world]??[];
  const hasSecret=Boolean(secret);
  const activeSnapshot=JSON.stringify(active);
  const isUnsaved=savedSnapshot !== '' && activeSnapshot !== savedSnapshot;

  useEffect(()=>{setSecret(window.sessionStorage.getItem(SECRET_KEY)||'');},[]);
  useEffect(()=>{if(secret)window.sessionStorage.setItem(SECRET_KEY,secret);},[secret]);
  useEffect(()=>{setSavedSnapshot(JSON.stringify(active)); setMessage('Preview updated from the current saved draft/live data.');},[world]);
  useEffect(()=>{if(savedSnapshot && activeSnapshot !== savedSnapshot) setMessage('Preview updated. Unsaved changes are visible only in Studio until you save or publish.');},[activeSnapshot,savedSnapshot]);

  async function runAuthenticated(action:Exclude<PendingAction,null>){
    if(saving) return;
    if(!secret){setPending(action);setSection('publishing');setMessage('Studio Secret required. Your unsaved editor state is preserved; authenticate to continue.');return;}
    setSaving(true); setMessage(action==='draft'?'Saving draft to Supabase…':'Publishing changes to the live world…');
    const ok= action==='draft' ? await saveDraft(world,secret) : await publishWorld(world,secret,`${worldInfo.label} publish`);
    setSaving(false);
    if(ok){setPending(null);setSavedSnapshot(JSON.stringify(settings[world]));setMessage(action==='draft'?'Draft saved to Supabase. Hard refresh and authenticated devices will load it in Studio.':'Published. The public world now loads these settings from Supabase.');}
    else {setPending(action);setSection('publishing');setMessage('Save failed. Check the Studio Secret, Supabase table permissions, and server environment variables, then retry.');}
  }
  function authenticate(){ if(!secret.trim()){setMessage('Enter the Studio Secret to continue.');return;} window.sessionStorage.setItem(SECRET_KEY,secret); const next=pending; setPending(null); setMessage('Studio access unlocked for this browser session.'); if(next && next !== 'upload') void runAuthenticated(next); }
  function openPreview(){window.open(worldInfo.preview,'_blank','noopener,noreferrer');}
  async function upload(file:File){
    if(!secret){setPending('upload');setSection('publishing');setMessage('Authenticate before uploading media. Your layer draft is preserved.');return;}
    setUploading(true);setMessage('Uploading media asset…');
    try{const form=new FormData();form.append('file',file);form.append('world',world);const response=await fetch('/api/world-design/upload',{method:'POST',headers:{'x-harmonic-studio-key':secret},body:form});const data=await response.json();if(!response.ok)throw new Error(data.error||'Upload failed');setDraft((current)=>({...current,url:data.url,kind:data.type}));setMessage('Upload complete. Add the layer to preview it immediately.');}
    catch(error){setMessage(error instanceof Error?error.message:'Upload failed.');}finally{setUploading(false);}
  }
  const preview=<LiveWorldPreview world={worldInfo.engineSlug} active={active} viewport={viewport} highlighted={section} />;

  useEffect(()=>{function handleStudioShortcut(event:KeyboardEvent){if(!(event.metaKey||event.ctrlKey))return;const key=event.key.toLowerCase();if(event.key.toLowerCase()==='z'){event.preventDefault();if(event.shiftKey)editorHistory.redo();else editorHistory.undo();}if(event.key.toLowerCase()==='s'){event.preventDefault();void runAuthenticated('draft');}}window.addEventListener('keydown',handleStudioShortcut);return()=>window.removeEventListener('keydown',handleStudioShortcut);},[editorHistory]);

  return <div className="mx-auto max-w-[96rem] pb-28 text-white">
    <EditorCommandBar canUndo={editorHistory.canUndo} canRedo={editorHistory.canRedo} isUnsaved={isUnsaved} saving={saving} onUndo={editorHistory.undo} onRedo={editorHistory.redo} onSaveDraft={()=>void runAuthenticated('draft')} onPublish={()=>void runAuthenticated('publish')} />
    <header className="rounded-[2.5rem] border border-white/10 bg-black/45 p-6 backdrop-blur-2xl sm:p-9"><p className="text-xs font-black uppercase tracking-[.34em] text-white/35">Design Department · Studio Repair</p><h1 className="mt-3 text-5xl font-black tracking-[-.07em] sm:text-7xl">World Design Studio</h1><p className="mt-4 max-w-3xl text-base leading-8 text-white/55">Edit and preview the same draft state side by side. Save Draft is private; Publish Changes updates the public world.</p></header>
    <div className="mt-5 flex rounded-full border border-white/10 bg-black/45 p-1 lg:hidden"><button onClick={()=>setMobileMode('edit')} className={`flex-1 rounded-full px-4 py-3 text-sm font-black ${mobileMode==='edit'?'bg-white text-black':'text-white/60'}`}>Edit</button><button onClick={()=>setMobileMode('preview')} className={`flex-1 rounded-full px-4 py-3 text-sm font-black ${mobileMode==='preview'?'bg-white text-black':'text-white/60'}`}>Preview</button></div>
    <div className="mt-6 grid gap-5 lg:grid-cols-[minmax(420px,0.9fr)_minmax(520px,1.1fr)]">
      <section ref={scrollRef} className={`${mobileMode==='preview'?'hidden lg:block':'block'} rounded-[2.4rem] border border-white/10 bg-black/45 p-5 backdrop-blur-2xl sm:p-7`}>
        <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.24em] text-white/35">Editing</p><h2 className="mt-2 text-4xl font-black tracking-[-.06em]">{worldInfo.label}</h2><Status status={cloudStatus} saving={saving} unsaved={isUnsaved} message={message}/></div><div className="flex flex-wrap gap-2"><button onClick={()=>runAuthenticated('draft')} disabled={saving} className="rounded-full border border-white/10 px-4 py-3 text-xs font-black disabled:opacity-40">Save Draft</button><button onClick={()=>confirm(`Publish ${worldInfo.label} to the public world?`)&&runAuthenticated('publish')} disabled={saving} className="rounded-full bg-purple-200 px-5 py-3 text-xs font-black text-black disabled:opacity-40">Publish Changes</button><button onClick={()=>{resetWorld(world);setMessage('Unsaved changes reset to the default world configuration.')}} disabled={saving} className="rounded-full border border-red-300/20 px-4 py-3 text-xs font-black text-red-100">Reset Unsaved Changes</button></div></div>
        <div className="mt-5 grid gap-2 sm:grid-cols-2">{worlds.map((item)=><button key={item.key} onClick={()=>{setWorld(item.key);setSection('identity');}} className={`rounded-2xl border p-3 text-left transition ${world===item.key?'border-white/25 bg-white/12':'border-white/8 bg-white/[.025]'}`}><p className="font-black">{item.label}</p><p className="mt-1 text-xs leading-5 text-white/38">{item.description}</p></button>)}</div>
        <nav className="mt-6 grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{sections.map((item)=><button key={item.key} onClick={()=>setSection(item.key)} className={`rounded-2xl border p-4 text-left ${section===item.key?'border-white/30 bg-white text-black':'border-white/10 bg-white/[.035]'}`}><p className="font-black">{item.label}</p><p className={`mt-1 text-xs leading-5 ${section===item.key?'text-black/55':'text-white/35'}`}>{item.description}</p></button>)}</nav>
        {section==='identity'&&<div className="mt-7 grid gap-4 sm:grid-cols-2"><Field label="World Title" value={active.title??''} onChange={(title)=>updateWorld(world,{title})}/><Field label="World Description" value={active.subtitle??''} onChange={(subtitle)=>updateWorld(world,{subtitle})} multiline/><Field label="Frequency Label" value={active.labels.eyebrow??''} onChange={(value)=>updateLabel(world,'eyebrow',value)}/><Field label="World Icon / Logo URL" value={active.media.find((a)=>a.placement==='logo')?.url??''} onChange={(url)=>updateLabel(world,'logoUrl',url)}/><RevertButton onClick={()=>{updateWorld(world,JSON.parse(savedSnapshot||activeSnapshot));setMessage('Current section reverted to the last saved draft snapshot.')}}/></div>}
        {section==='theme'&&<div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{([['primary','Primary Actions'],['secondary','Secondary Actions'],['accent','Accent / Highlights'],['background','World Background'],['surface','Panels / Cards'],['text','Main Text'],['muted','Muted Text'],['border','Borders / Dividers'],['glow','Glow / Energy']] as const).map(([key,label])=><ColorField key={key} label={label} value={active[key]} onChange={(value)=>updateWorld(world,{[key]:value})}/>)}<Select label="Typography Scale" value={active.labels.typographyScale??'balanced'} options={['compact','balanced','large','poster']} onChange={(value)=>updateLabel(world,'typographyScale',value)}/><Field label="Visual Atmosphere" value={active.labels.atmosphere??''} onChange={(value)=>updateLabel(world,'atmosphere',value)} multiline/></div>}
        {section==='copy'&&<div className="mt-7"><Panel title="Page Copy" note="All copy updates the live preview immediately."><div className="grid gap-4 sm:grid-cols-2">{[...sharedCopy,...extraCopy].map(([key,label])=><Field key={key} label={label} value={key==='title'?active.title??'':key==='subtitle'?active.subtitle??'':active.labels[key]??''} onChange={(value)=>key==='title'?updateWorld(world,{title:value}):key==='subtitle'?updateWorld(world,{subtitle:value}):updateLabel(world,key,value)} multiline={key.toLowerCase().includes('description')||key==='subtitle'}/>)}</div></Panel></div>}
        {section==='media'&&<div className="mt-7 grid gap-6"><Panel title="Add Any Visual" note="Upload or paste a hosted image, GIF, SVG, MP4, or WebM URL."><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Layer Name" value={draft.name} onChange={(name)=>setDraft({...draft,name})}/><Field label="Asset URL" value={draft.url} onChange={(url)=>setDraft({...draft,url})}/><label className="rounded-2xl border border-white/10 p-4"><span className="text-xs font-black uppercase tracking-widest text-white/35">Upload File</span><input type="file" accept="image/*,video/*" disabled={uploading} onChange={(e)=>e.target.files?.[0]&&upload(e.target.files[0])} className="mt-3 block w-full text-sm"/><span className="mt-2 block text-xs text-white/35">{uploading?'Uploading…':'Images, GIFs, SVG, MP4, WebM · max 50 MB'}</span></label><Select label="Type" value={draft.kind} options={['image','video']} onChange={(kind)=>setDraft({...draft,kind:kind as WorldMediaAsset['kind']})}/><Select label="Placement" value={draft.placement} options={['background','hero','logo','floating','section']} onChange={(placement)=>setDraft({...draft,placement:placement as WorldMediaAsset['placement']})}/><Select label="Fit" value={draft.fit} options={['contain','cover']} onChange={(fit)=>setDraft({...draft,fit:fit as WorldMediaAsset['fit']})}/></div><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><NumberField label="X Position %" value={draft.x} onChange={(x)=>setDraft({...draft,x})}/><NumberField label="Y Position %" value={draft.y} onChange={(y)=>setDraft({...draft,y})}/><NumberField label="Width %" value={draft.width} onChange={(width)=>setDraft({...draft,width})}/><NumberField label="Opacity %" value={draft.opacity} onChange={(opacity)=>setDraft({...draft,opacity})}/><NumberField label="Layer Order" value={draft.zIndex} onChange={(zIndex)=>setDraft({...draft,zIndex})}/></div><button disabled={!draft.url} onClick={()=>{addMedia(world,draft);setDraft(blankAsset);}} className="mt-5 rounded-full bg-white px-5 py-4 text-sm font-black text-black disabled:opacity-30">Add Layer to {worldInfo.label}</button></Panel><Panel title="Active Layers" note="All layers remain editable and reusable.">{active.media.length===0?<p className="text-white/40">No custom media yet.</p>:<div className="grid gap-4">{active.media.map((asset)=><MediaEditor key={asset.id} asset={asset} onChange={(patch)=>updateMedia(world,asset.id,patch)} onRemove={()=>removeMedia(world,asset.id)}/>)}</div>}</Panel></div>}
        {section==='layout'&&<Panel title="Layout Controls" note="Controls update preview cards, spacing, and visibility metadata."><div className="grid gap-4 sm:grid-cols-2"><Select label="Layout Preset" value={active.layoutPreset??'cinematic'} options={['cinematic','editorial','grid','minimal']} onChange={(layoutPreset)=>updateWorld(world,{layoutPreset})}/><Select label="Card Radius" value={active.labels.cardRadius??'rounded'} options={['sharp','rounded','pill']} onChange={(value)=>updateLabel(world,'cardRadius',value)}/><Select label="Spacing" value={active.labels.spacing??'comfortable'} options={['tight','comfortable','spacious']} onChange={(value)=>updateLabel(world,'spacing',value)}/><Select label="Feature Visibility" value={active.labels.featuresVisible??'all'} options={['all','hero-only','hide-community','hide-commerce']} onChange={(value)=>updateLabel(world,'featuresVisible',value)}/></div></Panel>}
        {section==='motion'&&<Panel title="Motion" note="Preview-safe motion settings; production rendering can consume these labels without analytics side effects."><div className="grid gap-4 sm:grid-cols-2"><Select label="Entry Animation" value={active.labels.entryMotion??'fade'} options={['none','fade','slide-up','float','pulse']} onChange={(value)=>updateLabel(world,'entryMotion',value)}/><Select label="Hover Behavior" value={active.labels.hoverMotion??'lift'} options={['none','lift','glow','scale']} onChange={(value)=>updateLabel(world,'hoverMotion',value)}/><Select label="Reduced Motion" value={active.labels.reducedMotion??'respect-system'} options={['respect-system','always-reduce']} onChange={(value)=>updateLabel(world,'reducedMotion',value)}/></div></Panel>}
        {section==='features'&&<Panel title="Features" note="Toggle world modules without leaving the Studio."><div className="grid gap-4 sm:grid-cols-2">{['Commerce','Audio','Community','Releases'].map((name)=><Select key={name} label={name} value={active.labels[`feature${name}`]??'enabled'} options={['enabled','preview-only','hidden']} onChange={(value)=>updateLabel(world,`feature${name}`,value)}/>)}</div></Panel>}
        {section==='publishing'&&<div className="mt-7"><Panel title="Publishing Access" note="The Studio Secret stays in sessionStorage only. It is not stored in localStorage, URLs, logs, or page source."><div className="grid gap-4 sm:grid-cols-[1fr_auto]"><Field label="Studio Secret" value={secret} onChange={setSecret}/><button onClick={authenticate} disabled={saving} className="rounded-full bg-white px-6 py-4 text-sm font-black text-black">{hasSecret?'Retry Pending Action':'Authenticate Session'}</button></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Info title="Cloud Status" text={cloudStatus}/><Info title="Last Saved" text={lastSavedAt?new Date(lastSavedAt).toLocaleString():'No save this session'}/><Info title="Access" text={hasSecret?'Unlocked for this browser session':'Secret required before saving'}/></div><div className="mt-4 flex flex-wrap gap-3"><button onClick={()=>runAuthenticated('draft')} disabled={saving} className="rounded-full border border-white/15 px-5 py-3 text-sm font-black">Save Draft</button><button onClick={()=>confirm(`Publish ${worldInfo.label}?`)&&runAuthenticated('publish')} disabled={saving} className="rounded-full bg-purple-200 px-5 py-3 text-sm font-black text-black">Publish Changes</button><button onClick={()=>copyToAll(world)} className="rounded-full bg-white px-5 py-3 text-sm font-black text-black">Apply Design to All Worlds</button></div></Panel><Phase4WorldRuntime world={world} secret={secret}/></div>}
      </section>
      <aside className={`${mobileMode==='edit'?'hidden lg:block':'block'} ${fullscreen?'fixed inset-3 z-50 overflow-auto rounded-[2rem] bg-black p-4':'lg:sticky lg:top-5 lg:h-[calc(100vh-2.5rem)]'}`}><div className="mb-3 flex flex-wrap items-center justify-between gap-2 rounded-2xl border border-white/10 bg-black/70 p-3"><div>{isUnsaved&&<span className="rounded-full bg-amber-300 px-3 py-1 text-xs font-black text-black">Previewing unsaved changes</span>}</div><div className="flex flex-wrap gap-2">{(['desktop','tablet','mobile'] as const).map((v)=><button key={v} onClick={()=>setViewport(v)} className={`rounded-full px-3 py-2 text-xs font-black ${viewport===v?'bg-white text-black':'border border-white/10 text-white/60'}`}>{v}</button>)}<button onClick={()=>setFullscreen(!fullscreen)} className="rounded-full border border-white/10 px-3 py-2 text-xs font-black">Preview Full Screen</button><button onClick={openPreview} className="rounded-full border border-white/10 px-3 py-2 text-xs font-black">Open Live World in New Tab</button></div></div>{preview}</aside>
    </div>
  </div>;
}

function Status({status,saving,unsaved,message}:{status:string;saving:boolean;unsaved:boolean;message:string}){return <div className="mt-2 rounded-2xl border border-white/10 bg-black/35 p-3"><p className="text-xs font-black uppercase tracking-[.18em] text-white/45">{saving?'Saving':unsaved?'Unsaved changes':status==='draft-saved'?'Draft saved':status==='published'?'Published':status==='error'?'Save failed':status==='dirty'?'Preview updated':'Ready'}</p><p className="mt-1 text-xs leading-5 text-white/55">{message}</p></div>}
function Panel({title,note,children}:{title:string;note:string;children:React.ReactNode}){return <section className="mb-5 rounded-[2rem] border border-white/10 bg-white/[.025] p-5"><h3 className="text-2xl font-black">{title}</h3><p className="mb-5 mt-2 text-sm leading-6 text-white/40">{note}</p>{children}</section>}
function Field({label,value,onChange,multiline=false}:{label:string;value:string;onChange:(value:string)=>void;multiline?:boolean}){return <label className="grid gap-2 rounded-2xl border border-white/10 bg-black/20 p-4"><span className="text-xs font-black uppercase tracking-widest text-white/35">{label}</span>{multiline?<textarea value={value} onChange={(e)=>onChange(e.target.value)} className="min-h-28 rounded-xl border border-white/10 bg-black/40 p-3 outline-none"/>:<input value={value} onChange={(e)=>onChange(e.target.value)} className="rounded-xl border border-white/10 bg-black/40 p-3 outline-none"/>}</label>}
function ColorField({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="grid gap-3 rounded-2xl border border-white/10 bg-black/20 p-4"><span className="text-xs font-black uppercase tracking-widest text-white/35">{label}</span><div className="grid grid-cols-[56px_1fr] gap-3"><input type="color" value={value} onChange={(e)=>onChange(e.target.value)} className="h-12 w-14 rounded-xl border-0 bg-transparent"/><input value={value} onChange={(e)=>onChange(e.target.value)} className="rounded-xl border border-white/10 bg-black/40 p-3 font-mono text-xs outline-none"/></div></label>}
function NumberField({label,value,onChange}:{label:string;value:number;onChange:(value:number)=>void}){return <label className="grid gap-2 rounded-2xl border border-white/10 bg-black/20 p-4"><span className="text-xs font-black uppercase tracking-widest text-white/35">{label}</span><input type="number" value={value} onChange={(e)=>onChange(Number(e.target.value))} className="rounded-xl border border-white/10 bg-black/40 p-3 outline-none"/></label>}
function Select({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(value:string)=>void}){return <label className="grid gap-2 rounded-2xl border border-white/10 bg-black/20 p-4"><span className="text-xs font-black uppercase tracking-widest text-white/35">{label}</span><select value={value} onChange={(e)=>onChange(e.target.value)} className="rounded-xl border border-white/10 bg-black/40 p-3 outline-none">{options.map((option)=><option key={option}>{option}</option>)}</select></label>}
function RevertButton({onClick}:{onClick:()=>void}){return <button onClick={onClick} className="rounded-2xl border border-amber-200/20 bg-amber-200/10 p-4 text-left text-sm font-black text-amber-100">Before / After: revert this section to last saved snapshot</button>}
function Info({title,text}:{title:string;text:string}){return <div className="rounded-2xl border border-white/10 bg-black/20 p-4"><p className="text-xs font-black uppercase tracking-widest text-white/35">{title}</p><p className="mt-2 text-sm font-bold">{text}</p></div>}
function MediaEditor({asset,onChange,onRemove}:{asset:WorldMediaAsset;onChange:(patch:Partial<WorldMediaAsset>)=>void;onRemove:()=>void}){return <div className="rounded-2xl border border-white/10 bg-black/20 p-4"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Name" value={asset.name} onChange={(name)=>onChange({name})}/><Field label="URL" value={asset.url} onChange={(url)=>onChange({url})}/><Select label="Placement" value={asset.placement} options={['background','hero','logo','floating','section']} onChange={(placement)=>onChange({placement:placement as WorldMediaAsset['placement']})}/><NumberField label="Width %" value={asset.width} onChange={(width)=>onChange({width})}/><NumberField label="X %" value={asset.x} onChange={(x)=>onChange({x})}/><NumberField label="Y %" value={asset.y} onChange={(y)=>onChange({y})}/><NumberField label="Opacity %" value={asset.opacity} onChange={(opacity)=>onChange({opacity})}/><NumberField label="Layer Order" value={asset.zIndex} onChange={(zIndex)=>onChange({zIndex})}/></div><button onClick={onRemove} className="mt-4 rounded-full border border-red-300/20 px-4 py-2 text-xs font-black text-red-200">Remove Layer</button></div>}
function LiveWorldPreview({world,active,viewport,highlighted}:{world?:string;active:ReturnType<typeof useWorldCustomization>['settings'][WorldKey];viewport:Viewport;highlighted:Section}){const engine=world?getWorldBySlug(world):null;const previewWorld: HarmonicWorldConfig | null=engine?{...engine,name:active.title||engine.name,tagline:active.subtitle||engine.tagline,primary:active.primary,secondary:active.secondary,accent:active.accent,atmosphere:active.labels.atmosphere||engine.atmosphere,rooms:engine.rooms.map((room,index)=>({...room,label:active.labels[`room${index}Label`]||room.label,description:active.labels[`room${index}Description`]||room.description,cta:active.labels.primaryCta||room.cta}))}:null;return <div className={`mx-auto h-full overflow-auto rounded-[2rem] border bg-black ${viewport==='desktop'?'max-w-full':viewport==='tablet'?'max-w-3xl':'max-w-sm'}`} style={{borderColor:active.border,background:active.background,color:active.text,boxShadow:`0 0 50px ${active.glow}33`}}><div className="sticky top-0 z-10 border-b border-white/10 bg-black/80 px-4 py-2 text-xs font-black uppercase tracking-[.18em] text-white/45">Preview section: {highlighted}</div>{active.media.filter((asset)=>asset.placement==='background').map((asset)=><MediaLayer key={asset.id} asset={asset}/>) }{previewWorld?<WorldEngineShell world={previewWorld} previewMode />:<div className="p-8"><p className="text-xs font-black uppercase tracking-[.25em]" style={{color:active.secondary}}>{active.labels.eyebrow||'Live Preview'}</p><h2 className="mt-4 text-5xl font-black">{active.title}</h2><p className="mt-3 leading-7" style={{color:active.muted}}>{active.subtitle}</p></div>}{active.media.filter((asset)=>asset.placement!=='background').map((asset)=><MediaLayer key={asset.id} asset={asset}/>)}</div>}
function MediaLayer({asset}:{asset:WorldMediaAsset}){const style={left:`${asset.x}%`,top:`${asset.y}%`,width:`${asset.width}%`,opacity:asset.opacity/100,transform:`translate(-50%,-50%) rotate(${asset.rotation}deg)`,zIndex:asset.zIndex} as const;return <div className="pointer-events-none absolute" style={style}>{asset.kind==='video'?<video src={asset.url} autoPlay={asset.loop} loop={asset.loop} muted={asset.muted} className="w-full rounded-2xl"/>:<img src={asset.url} alt={asset.name} className="w-full rounded-2xl"/>}</div>}
