'use client';

import Link from 'next/link';
import { bootRuntime } from '@/lib/harmonic-signal-bus';
import { worldDefaults } from '@/lib/harmonic-engine';
import { RuntimeVisualDriver } from '@/components/runtime/RuntimeVisualDriver';
import { LivingWorldOverlay } from '@/components/runtime/LivingWorldOverlay';
import { SeasonalWorldLayer } from '@/components/seasons/SeasonalWorldLayer';
import { WorldCopy } from '@/components/studio/WorldCopy';
import { WorldStructuredRuntime } from '@/components/runtime/WorldStructuredRuntime';
import { useWorldCustomization, type WorldMediaAsset } from '@/components/studio/WorldCustomizationProvider';

const runtime=bootRuntime(worldDefaults.schmackin);
const tiers=[
 ['SCHMACKINN','Elite dishes. Top tier only.','∞','#c43cff'],
 ['CRACKINN','Solid eats. Really hittin’.','ϟ','#ffd21c'],
 ['LACKINN','Mid. Could be better.','☹','#ff5a28'],
 ['BUNS','Not it. Save your money.','⌫','#9ca3af'],
] as const;
const plates=['Jerk Mac Bowl','Philly Loaded Fries','Lemon Pepper Wings','Shrimp Alfredo Pasta'];

function mediaFor(media:WorldMediaAsset[],placement:WorldMediaAsset['placement'],section?:string){return media.find(a=>a.visible!==false&&a.placement===placement&&(!section||a.section===section));}
function Stars({value=4}:{value?:number}){return <span aria-label={`${value} out of 5`} className="tracking-[.16em]">{Array.from({length:5},(_,i)=><span key={i} className={i<value?'text-fuchsia-400':'text-white/20'}>∞</span>)}</span>}
function Frame({children,className=''}:{children:React.ReactNode;className?:string}){return <section className={`mx-auto w-full max-w-[1500px] px-3 py-2 sm:px-5 ${className}`}>{children}</section>}
function Panel({children,className=''}:{children:React.ReactNode;className?:string}){return <div className={`rounded-xl border border-fuchsia-400/25 bg-black/78 shadow-[0_0_34px_rgba(168,85,247,.09),inset_0_0_28px_rgba(168,85,247,.025)] backdrop-blur-xl ${className}`}>{children}</div>}
function Asset({asset,className=''}:{asset?:WorldMediaAsset;className?:string}){if(!asset)return null;return asset.kind==='video'?<video src={asset.url} autoPlay loop={asset.loop} muted={asset.muted} playsInline className={className}/>:<img src={asset.url} alt={asset.alt||asset.name} className={className}/>}

export function SchmackinnWorldExperience(){
 const {settings}=useWorldCustomization();const active=settings.schmackinn;const media=active.media;
 const sections=[
  {id:'hero',node:<Hero media={media}/>},{id:'featured',node:<Featured media={media}/>},{id:'collections',node:<TierArchive/>},
  {id:'community',node:<Community media={media}/>},{id:'archive',node:<Archive/>},{id:'commerce',node:<Commerce/>},{id:'audio',node:<AudioLayer/>},
 ];
 return <main className="world-customizable relative isolate min-h-screen overflow-hidden pb-8 text-white" style={{background:active.background,color:active.text}}>
  <SeasonalWorldLayer world="schmackin"/><RuntimeVisualDriver world="schmackin"/><LivingWorldOverlay world="schmackin"/>
  <div className="pointer-events-none fixed inset-0 -z-30 bg-[radial-gradient(circle_at_75%_12%,rgba(147,51,234,.24),transparent_28%),radial-gradient(circle_at_12%_62%,rgba(217,70,239,.12),transparent_30%),linear-gradient(180deg,#020104,#07020b_45%,#020104)]"/>
  <div className="pointer-events-none fixed inset-0 -z-20 opacity-30 [background-image:linear-gradient(rgba(168,85,247,.05)_1px,transparent_1px),linear-gradient(90deg,rgba(168,85,247,.05)_1px,transparent_1px)] [background-size:32px_32px]"/>
  {media.filter(a=>a.visible!==false&&a.placement==='background').map(a=><Asset key={a.id} asset={a} className="pointer-events-none fixed inset-0 -z-10 h-full w-full object-cover opacity-25"/>)}
  <Header/><WorldStructuredRuntime world="schmackinn" sections={sections}/><Footer/>
  <span className="sr-only">Runtime DNA {runtime.state.dna.food}</span>
 </main>;
}

function Header(){return <header className="sticky top-0 z-40 border-b border-fuchsia-300/20 bg-black/90 backdrop-blur-2xl"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4 px-5 py-4"><Link href="/" className="text-xl font-black italic tracking-[-.06em] text-fuchsia-300 [text-shadow:0_0_18px_rgba(217,70,239,.8)]">HARMONIC OS</Link><nav className="hidden gap-8 text-[10px] font-black uppercase tracking-[.18em] text-white/75 md:flex"><Link href="/">Home</Link><Link href="/worlds">Worlds⌄</Link><Link href="/about">About</Link><Link href="/community">Community</Link><Link href="/shop">Shop</Link></nav><div className="grid h-11 w-11 place-items-center rounded-xl border border-fuchsia-300/45 text-2xl text-fuchsia-300 shadow-[0_0_22px_rgba(217,70,239,.3)]">∞</div></div></header>}

function Hero({media}:{media:WorldMediaAsset[]}){const hero=mediaFor(media,'hero','hero')||mediaFor(media,'hero');return <Frame><Panel className="overflow-hidden"><div className="grid min-h-[390px] lg:grid-cols-[.78fr_1.22fr]"><div className="relative z-10 flex flex-col justify-center p-7 sm:p-10"><p className="text-4xl font-black italic leading-[.88] tracking-[-.07em] text-white sm:text-6xl">GOT THE <span className="block text-fuchsia-400 [text-shadow:0_0_24px_rgba(217,70,239,.75)]">MUNCHIES?</span></p><p className="mt-8 text-lg text-fuchsia-200/75">Welcome to</p><h1 className="text-4xl font-black tracking-[.03em] text-fuchsia-400"><WorldCopy world="schmackinn" field="title" fallback="SCHMACKINN"/></h1><p className="mt-3 max-w-sm text-sm leading-6 text-white/70"><WorldCopy world="schmackinn" field="subtitle" fallback="Real reviews. Real opinions. Find your next obsession."/></p><Link href="/worlds/schmackinn/reviews" className="mt-7 w-fit rounded border border-fuchsia-400/70 px-5 py-3 text-[10px] font-black uppercase tracking-[.18em] text-fuchsia-100 shadow-[0_0_20px_rgba(217,70,239,.2)]">Explore the world</Link></div><div className="relative min-h-[330px] overflow-hidden bg-[radial-gradient(circle_at_50%_46%,rgba(217,70,239,.5),transparent_20%),linear-gradient(125deg,#08000d,#21002f_55%,#040306)]">{hero?<Asset asset={hero} className="absolute inset-0 h-full w-full object-cover"/>:<><div className="absolute inset-0 opacity-50 [background-image:linear-gradient(115deg,transparent_35%,rgba(232,121,249,.16),transparent_65%)]"/><div className="absolute left-[52%] top-[46%] h-36 w-64 -translate-x-1/2 -translate-y-1/2 rotate-[-21deg] rounded-full border-[11px] border-fuchsia-300 shadow-[0_0_35px_#d946ef,inset_0_0_26px_#d946ef]"><div className="absolute -bottom-20 left-1/2 h-24 w-36 -translate-x-1/2 rounded-[50%] border-8 border-fuchsia-300/80 shadow-[0_0_28px_#d946ef]"/></div></>}<div className="absolute right-8 top-8 rounded border border-red-400/50 bg-black/65 px-4 py-3 text-center text-sm font-black tracking-widest text-red-300 shadow-[0_0_20px_rgba(248,113,113,.35)]">GOOD FOOD<br/>GOOD MOOD</div></div></div></Panel></Frame>}

function Featured({media}:{media:WorldMediaAsset[]}){const featured=mediaFor(media,'section','featured')||media.find(a=>a.visible!==false&&a.placement==='section');return <Frame><div className="grid gap-2 lg:grid-cols-[1.35fr_.65fr]"><Panel className="p-4"><p className="text-xs font-black uppercase tracking-[.18em] text-fuchsia-200">☆ Featured Review</p><div className="mt-3 grid gap-4 sm:grid-cols-[1.05fr_.95fr]"><div className="relative min-h-56 overflow-hidden rounded-xl bg-[radial-gradient(circle_at_50%_25%,#b45309,#4a1707_48%,#110604)]">{featured?<Asset asset={featured} className="absolute inset-0 h-full w-full object-cover"/>:<div className="grid h-full min-h-56 place-items-center text-8xl">🍗</div>}<button className="absolute left-1/2 top-1/2 grid h-14 w-14 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border border-fuchsia-200/50 bg-black/80 text-xl text-fuchsia-200 shadow-[0_0_25px_rgba(217,70,239,.5)]">▶</button></div><div className="flex flex-col justify-center"><h2 className="text-3xl font-black">THE HOT SPOT</h2><p className="mt-2 text-white/60">Chicken & Waffles</p><p className="mt-6 text-[10px] font-black uppercase text-fuchsia-300">Schmackinn</p><p className="mt-2 text-2xl"><Stars value={4}/></p><Link href="/worlds/schmackinn/reviews" className="mt-5 w-fit rounded border border-fuchsia-300/45 px-4 py-2 text-[10px] font-black uppercase tracking-[.16em]">Watch now</Link></div></div></Panel><Panel className="p-4"><p className="text-xs font-black uppercase tracking-[.18em] text-fuchsia-200">Trending Plates</p><div className="mt-3 space-y-2">{plates.map((plate,index)=><div key={plate} className="flex items-center gap-3 rounded-lg border border-white/5 bg-white/[.02] p-2"><div className="grid h-12 w-16 place-items-center overflow-hidden rounded-lg bg-amber-950 text-xl">🍽️</div><p className="flex-1 text-xs font-bold">{plate}</p><Stars value={index===3?3:4}/></div>)}</div></Panel></div></Frame>}

function TierArchive(){return <Frame><Panel className="p-4"><p className="text-xs font-black uppercase tracking-[.18em] text-fuchsia-200">☆ Tier Archive</p><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{tiers.map(([name,desc,icon,color])=><Link href="/worlds/schmackinn/reviews" key={name} className="rounded-xl border bg-black/75 p-5 text-center transition hover:-translate-y-1" style={{borderColor:color,boxShadow:`0 0 24px ${color}22`,color}}><p className="text-2xl font-black">{name}</p><p className="my-4 text-5xl">{icon}</p><p className="text-xs leading-5 text-white/60">{desc}</p></Link>)}</div></Panel></Frame>}

function Community({media}:{media:WorldMediaAsset[]}){const map=mediaFor(media,'section','map');return <Frame><div className="grid gap-2 lg:grid-cols-3"><Panel className="p-4"><p className="text-xs font-black uppercase tracking-[.18em] text-fuchsia-200">Restaurant Map</p><div className="relative mt-3 h-48 overflow-hidden rounded-xl border border-fuchsia-400/15 bg-[#08040d]">{map?<Asset asset={map} className="absolute inset-0 h-full w-full object-cover opacity-80"/>:<><div className="absolute inset-0 opacity-40 [background-image:linear-gradient(rgba(217,70,239,.14)_1px,transparent_1px),linear-gradient(90deg,rgba(217,70,239,.14)_1px,transparent_1px)] [background-size:26px_26px]"/>{[[18,33],[31,61],[49,24],[63,70],[78,38],[87,65]].map(([x,y],i)=><span key={i} className="absolute text-2xl text-fuchsia-400 [text-shadow:0_0_12px_#d946ef]" style={{left:`${x}%`,top:`${y}%`}}>⌖</span>)}</>}<Link href="/worlds/schmackinn/map" className="absolute bottom-3 left-3 rounded border border-fuchsia-300/50 bg-black/75 px-3 py-2 text-[10px] font-black uppercase">Explore map</Link></div></Panel><Panel className="p-4"><p className="text-xs font-black uppercase tracking-[.18em] text-fuchsia-200">Community Picks</p><div className="mt-4 space-y-4">{['That jerk bowl CRACKIN','Shrimp Alfredo hits','Wings were buns'].map((text,i)=><div key={text} className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-fuchsia-950 text-xs">{i+1}</div><div className="min-w-0 flex-1"><p className="text-xs text-white/75">{text}</p><p className="mt-1 text-[9px] uppercase text-fuchsia-300">Schmackinn</p></div><Stars value={i===2?2:4}/></div>)}</div></Panel><Panel className="p-4"><p className="text-xs font-black uppercase tracking-[.18em] text-fuchsia-200">Hidden Recipe Archive</p><p className="mt-5 text-sm leading-6 text-white/65">Exclusive recipes from our favorite spots.</p><div className="mt-8 flex items-end justify-between"><span className="rounded border border-fuchsia-300/45 px-3 py-2 text-[10px] font-black uppercase">Coming soon</span><span className="text-6xl text-fuchsia-300">♨</span></div></Panel></div></Frame>}
function Archive(){return <Frame><Panel className="p-5"><p className="text-xs font-black uppercase tracking-[.18em] text-fuchsia-200">Food Memory Archive</p><h2 className="mt-2 text-2xl font-black">Every plate leaves a frequency.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/55">Save restaurants, jokes, people, cities, and first bites that became part of the story.</p></Panel></Frame>}
function Commerce(){return <Frame><Panel className="flex flex-wrap items-center justify-between gap-5 p-5"><div><p className="text-xs font-black uppercase tracking-[.18em] text-fuchsia-200">Flavor Pass</p><h2 className="mt-2 text-2xl font-black">Unlock private tastings and drops.</h2></div><Link href="/shop" className="rounded bg-fuchsia-400 px-6 py-3 text-xs font-black uppercase tracking-[.15em] text-black">Enter shop</Link></Panel></Frame>}
function AudioLayer(){return <Frame><Panel className="flex items-center gap-4 p-4"><button className="grid h-12 w-12 place-items-center rounded-full bg-fuchsia-500 text-black">▶</button><div className="flex-1"><p className="text-xs font-black uppercase tracking-[.18em] text-fuchsia-200">Schmackinn Frequency</p><div className="mt-2 h-1 rounded-full bg-gradient-to-r from-fuchsia-500 via-purple-400 to-transparent"/></div><span className="text-xs text-white/40">LIVE</span></Panel></Frame>}
function Footer(){return <footer className="mx-auto mt-5 flex max-w-[1500px] items-center justify-between border-t border-fuchsia-300/15 px-5 py-7 text-[10px] font-black uppercase tracking-[.34em] text-fuchsia-200/65"><span>Stay in tune.</span><span className="text-xl text-fuchsia-300">⌁⌁⌁</span><span>∞ &nbsp; Stay in harmony.</span></footer>}
