-- Phase 4 Living Runtime: draft/preview/publish workflow and restorable versions.

alter table public.world_builder_designs
  add column if not exists draft_settings jsonb,
  add column if not exists live_settings jsonb,
  add column if not exists status text not null default 'draft',
  add column if not exists version integer not null default 0,
  add column if not exists published_at timestamptz;

update public.world_builder_designs
set draft_settings = coalesce(draft_settings, settings, '{}'::jsonb),
    live_settings = coalesce(live_settings, settings, '{}'::jsonb)
where draft_settings is null or live_settings is null;

create table if not exists public.world_builder_versions (
  id bigint generated by default as identity primary key,
  world text not null,
  version integer not null,
  label text not null default 'Published version',
  settings jsonb not null,
  created_at timestamptz not null default now(),
  unique (world, version)
);

alter table public.world_builder_versions enable row level security;

drop policy if exists "World builder versions are publicly readable" on public.world_builder_versions;
create policy "World builder versions are publicly readable"
  on public.world_builder_versions for select using (true);

create index if not exists world_builder_versions_world_created_idx
  on public.world_builder_versions (world, created_at desc);
